### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by rominf** [lambdamusic/OntoSPy#1]
Please add python 3 support.

**Comment by lambdamusic** [comment]
Sorry not a priority right now.. I'll keep it in mind though.

**Comment by T-002** [comment]
I created a pull request. With the updates, you will have a running version for Python 2 and 3.

**Comment by cbcunc** [comment]
If you aren't going to merge and release the pull request above, then please eliminate the Python 3 categories on Pypi as it is wasting other people's time:
https://pypi.python.org/pypi/ontospy
 Programming Language :: Python :: 2
Programming Language :: Python :: 2.6
Programming Language :: Python :: 2.7
Programming Language :: Python :: 3
Programming Language :: Python :: 3.2
Programming Language :: Python :: 3.3
Programming Language :: Python :: 3.4

**Comment by lambdamusic** [comment]
Hey - thanks for this, haven't had a chance to look at the pull request yet but it's in my todo list

Michele

**Comment by T-002** [comment]
Hi Michele,

I resolved the conflicts of the pull request.

Christian

**Comment by lambdamusic** [comment]
Merged - thanks T-002!
