### ISSUE TITLE
lov.okfn.org is defunct

### ISSUE THREAD

**Issue by jonassmedegaard** [lambdamusic/Ontospy#110]
Doing `ontospy utils -d` offers to scan from <http://lov.okfn.org> but that site is down (not sure if temporarily or permanently).

Maybe that site moved - it seems to be what is now offered at <https://lov.linkeddata.es> - and indeed changing code to use <https://lov.linkeddata.es/dataset/lov/api/v2/vocabulary/list> as baseuri works.

I recommend to list the normalized URI in the UI - i.s. add trailing `/`.

While at it, I recommend to switch the alternative <http://prefix.cc/popular/> to use secure `https` protocol - both the listing in UI and actual baseuri.

**Comment by jonassmedegaard** [comment]
I intend on carrying this patch for the Debian packaging on Ontospy: https://salsa.debian.org/debian/ontospy/-/blob/debian/master/debian/patches/1001_URIs.patch

**Comment by lambdamusic** [comment]
Many thanks for this! Added to https://github.com/lambdamusic/Ontospy/releases/tag/2.0.0-alpha
