### ISSUE TITLE
License

### ISSUE THREAD

**Issue by marqh** [lambdamusic/OntoSPy#2]
hello

I have recently come across your Ontospy library on Github and started
using it experimentally, I have made some useful progress and I would
like to thank you for your work and for publishing it for others to use.

I am reaching a point where I have some useful extension functionality
and I am considering code maintenance and management.

One key question I have is the license which ontospy is governed by?
The source on github does not appear to provide details on license.
Would you be willing to discuss this topic with me, with a view to
providing a license with the code?

all the best
mark

**Comment by lambdamusic** [comment]
Hi Mark, I've added a gpl-3.0 license to the code. 
hope this doesn't stop you from working on it. 
PS: I'm making a major release available soon!

**Comment by marqh** [comment]
Hi @lambdamusic 

GPL-3.0 statement is great news; thank you.
I look forward to a major release.  Do you have any tasters of what you have in store?

thank you
mark

**Comment by lambdamusic** [comment]
You're welcome :-) ...I released the 1.5 version yesterday. Better support for sparql and more command line options are the primary improvements. I'm working on some documentation too but that's not completed yet.
