### ISSUE TITLE
Bloated installation requirements

### ISSUE THREAD

**Issue by cthoyt** [lambdamusic/Ontospy#20]
While it's packed full of great features, unfortunately, the installation footprint of OntoSpy is rather large. 

Would you consider splitting this package into multiple components/plugins, such as the way that Flask, SQLAlchemy and other modules do?

My use case is just for parsing and programatic traversal of RDF/SKOS/OWL documents and have less interest in visualization/command line components. I can imagine other people might just have a use for one of these components, but not all.

**Comment by lambdamusic** [comment]
Thanks, that's a fair comment, it's something I've been meaning to do but never got down to.

**Comment by cthoyt** [comment]
I hope it's not annoying that I keep making suggestions to your library - if it's getting excessive I will stop :)

I have one more idea on how to do this easily, without changing much code - using the extras-require in setuptools it's possible to skip installing some of these dependencies (without changing any code) if a user isn't planning on using them (see PR #22 for how I used this to remove the readline dependency that's a bit problematic)

**Comment by lambdamusic** [comment]
FYI I've now separated out all the core APIs from the documentation library, which lives in the [OntoDocs](https://github.com/lambdamusic/Ontodocs) package. 
The requirements for OntoSpy are much more lightweight. 
Hope this helps!
