### ISSUE TITLE
Installation issue with package files

### ISSUE THREAD

**Issue by GMTG** [lambdamusic/Ontospy#25]
When running the ontospy installation command : pip install ontospy, I get the following error:

Running setup.py install for ontospy
    error: can't copy 'ontospy/viz/static/libs/Chart.js-2.4.0': doesn't exist or not a regular file

Could anyone help me to resolve this issue please ?

**Comment by GMTG** [comment]
For more details abouth the installation error, please find the following screenshot:
![image](https://cloud.githubusercontent.com/assets/10833524/22737193/465be036-ee02-11e6-98c9-2f9e4789d749.png)

**Comment by lambdamusic** [comment]
Hi, I've just released version 1.7.4 which should fix that [problem](http://stackoverflow.com/questions/3712033/python-distutils-error-directory-doesnt-exist-or-not-a-regular-file). 

Would you mind trying the latest version? 

```
pip install ontospy -U
```

**Comment by GMTG** [comment]
Thank you for your replay. But Actually, I do have the issue on the latest version. The previous version is working correctly for me !

**Comment by lambdamusic** [comment]
Sorry I am confused: your original message reported a problem with 1.7.3, but now you are saying  
> The previous version is working correctly for me !

Can you please specify which ontospy version you are trying to install (latest is 1.7.4)

**Comment by GMTG** [comment]
Actually, the installation process was successfull when installing version 1.6.2. However, didn't succeed to install neither version 1.7.3 nor 1.7.4; the same error messages are generated.

**Comment by lambdamusic** [comment]
ok it may be an issue with `readline` then (based on the screenshot you shared above). 
What OS are you on? I'll try to make this dependency optional in the next release.

**Comment by GMTG** [comment]
I have tried to installed it both on the latest version of 
Ubuntu 16.04.2 LTS (64bits) and also latest version of Kali 2

**Comment by lambdamusic** [comment]
I've removed the `readline` dependency on v 1.7.6

Hopefully this is going to fix your problem... let me know how it goes.

**Comment by lambdamusic** [comment]
Ok i'm closing this issue, assume it's working now :-)
