### ISSUE TITLE
typo in visualization template structure

### ISSUE THREAD

**Issue by NielsHoffmann** [lambdamusic/Ontospy#30]
I think there is a typo in the viz/builder.py script, line 41.
It refers to ONTOSPY_VIZ_TEMPLATES + "html-simple", whereas the folder is called html-single...

**Comment by NielsHoffmann** [comment]
Never mind, I see that you moved the viz stuff to a separate repo anyway.

**Comment by lambdamusic** [comment]
Thanks, I've fixed it and added a link here https://github.com/lambdamusic/Ontodocs/issues/1
