### ISSUE TITLE
Add ability to turn off the output of printDebug() when calling programatically 

### ISSUE THREAD

**Issue by Tombadil** [lambdamusic/OntoSPy#6]
When initialising a graph for use programmatically, the details of the ontology are printed (by _scan() called on init).  It would be great if this could be parameterised.

**Comment by lambdamusic** [comment]
Yap that was a bit too much to see in some cases. 

I've added a flag  `verbose` (defaults to True) which you can use when instantiating the Graph. So just set it to False and you shouldn't see those messages anymore..
