### ISSUE TITLE
Cannot specify preferred language for labels and descriptions

### ISSUE THREAD

**Issue by yuricus** [lambdamusic/Ontospy#63]
Hi! I'm trying to use Ontodocs on multi-lingual ontology and would like to have option to manage selected languages, at least - specify preferred language for labels and descriptions to be able to generate two versions of documentation.

**Comment by lambdamusic** [comment]
See https://github.com/lambdamusic/Ontospy/releases/tag/v1.9.9 for a first implementation of this feature:

EG `ontospy gendocs -l --preflabel label --preflang de`

**Comment by lambdamusic** [comment]
Improved support with https://github.com/lambdamusic/Ontospy/releases/tag/v1.9.9.1
