### ISSUE TITLE
add dependency to Pygmentize

### ISSUE THREAD

**Issue by VladimirAlexiev** [lambdamusic/Ontospy#70]
I guess Pygmentize is used to highlight the Turtle sources ("implementation" of each term). 
```
2) Html: multi-page
Loading graph...
Building visualization...
Error: Pygmentize Failed (30 times)
```
Add such dependency, or at least describe in the README how to install it.

**Comment by NiranjanTambe** [comment]
Hello all!
I am having the same problem :(
I have installed pygments. I have version 2.2.0
I also have php version 7.2.9

My error also says
ERROR: No matching distribution found for pygmentize

Please help!!
