### ISSUE TITLE
some subcommands outputs wrongly to STDERR

### ISSUE THREAD

**Issue by jonassmedegaard** [lambdamusic/Ontospy#76]
Running `ontospy gendocs --showtypes` outputs in color, which is disabled when not outputting to a tty.  Nice!

Not so nice, however, that output is to STDERR, confusingly leading to e.g. `ontospy gendocs --showtypes | grep -c ." outputting in color and getting wrong count.

Similar for `ontospy gendocs --showthemes | grep -c .`

Seems STDOUT and STDERR is swapped for those commands.

**Comment by lambdamusic** [comment]
Thanks for raising this. It'll be addressed in the upcoming version 1.9.9.1

**Comment by lambdamusic** [comment]
https://github.com/lambdamusic/Ontospy/releases/tag/v1.9.9.1
