### ISSUE TITLE
some subcommands always emit color hinting

### ISSUE THREAD

**Issue by jonassmedegaard** [lambdamusic/Ontospy#77]
The command `ontospy scan http://www.w3.org/2004/02/skos/core` emits its output in color.  Nice!

Not nice that this command does too: `ontospy scan http://www.w3.org/2004/02/skos/core | less`
...because less do not (in its default setup) parse console escape sequences.

Please make sure to (by default) emit terminal escape sequences only when connected to a TTY.

**Comment by lambdamusic** [comment]
Thanks for raising this. It'll be addressed in the upcoming version 1.9.9.1

**Comment by lambdamusic** [comment]
https://github.com/lambdamusic/Ontospy/releases/tag/v1.9.9.1
