### ISSUE TITLE
Error message suggests wrong command "ontospy --bootstrap"

### ISSUE THREAD

**Issue by jonassmedegaard** [lambdamusic/Ontospy#78]
Running `ontospy gendocs --lib` fails with the following error message:
```
Your local library is empty. Use 'ontospy --bootstrap' to add some ontologies to it.
```

The command `ontospy --bootstrap` does not exist, however.

Correct command seems to be `ontospy lib --bootstrap`

**Comment by lambdamusic** [comment]
Thanks, was fixed in https://github.com/lambdamusic/Ontospy/commit/fb778ee031157e376cd8140a16a7d03874f59ebe#diff-d3371ef67d5f601acefec8569cdd5354
