### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by jonassmedegaard** [lambdamusic/Ontospy#79]
I notice that commit eb46cb1 declared a version number in metadata of the project.

Please tag releases in git, to ease correlating them with sourcecode.  That is helpful e.g. for redistribution - I maintain packaging of IntoSpy for Debian where currently a conservative snapshot date is used as preliminary versioning of "releases": https://tracker.debian.org/pkg/ontospy

**Comment by lambdamusic** [comment]
That's a very good point. Thanks and will start doing this eg
https://github.com/lambdamusic/Ontospy/releases/tag/v1.9.8.3
