### ISSUE TITLE
configfile contains private and/or demo data

### ISSUE THREAD

**Issue by jonassmedegaard** [lambdamusic/Ontospy#80]
Newly added file <config.ini> contains the path </Users/michele.pasin/.ontospy/models/> which seems either accidentally leaked private data or example data.

I recommend to avoid filling in "dummy" data only in files clearly intended as examples - e.g. by placing such files below subdirectory <examples/> in source.

**Comment by lambdamusic** [comment]
Sorry that file ended up there by mistake
