### ISSUE TITLE
A command-line flag to avoid opening browser for gendocs

### ISSUE THREAD

**Issue by jindrichmynarz** [lambdamusic/Ontospy#81]
It would be useful to have a command-line flag for the `gendocs` command to avoid opening the generated documentation in a web browser (as done [here](https://github.com/lambdamusic/Ontospy/blob/master/ontospy/cli.py#L282-L284)), in particular in [non-interactive contexts](https://www.tldp.org/LDP/abs/html/intandnonint.html).

**Comment by lambdamusic** [comment]
Fixed with https://github.com/lambdamusic/Ontospy/releases/tag/v1.9.8.3
