### ISSUE TITLE
shell can't start without the readline library

### ISSUE THREAD

**Issue by greeve** [lambdamusic/Ontospy#86]
When I try starting the shell from the command line I get the warning:

`WARNING:` ontospy shell can't without the readline library.`

I had thought the readline dependency was removed in a previous version. I am using Python 3.6.6 and ontospy v1.9.8.2 on macOS Mojave.

**Comment by lambdamusic** [comment]
Correct, the `shell` relies on readline.

In past I made this feature optional, that's all (see https://github.com/lambdamusic/Ontospy/pull/22). 

NOTE It'd be nice to remove this dependency (eg in favor of [Python Prompt Toolkit](https://python-prompt-toolkit.readthedocs.io/en/master/)) but no time for doing this at the moment (help wanted!).
