### ISSUE TITLE
`--title` not adopted in all `outputtypes`

### ISSUE THREAD

**Issue by Zack-83** [lambdamusic/Ontospy#90]
Hallo,
using Ontospy in doc generating mode with output types 5, 7, 8, 9, 10 does not overtake the given `--title` 
My command: 
`ontospy gendocs --type 5 --title Metadata4Ing metadata4ing.ttl` 
Output:
![immagine](https://user-images.githubusercontent.com/37865804/82722230-169b7a80-9cc5-11ea-9769-a63b325f117d.png)

**Comment by lambdamusic** [comment]
Fixed with https://github.com/lambdamusic/Ontospy/releases/tag/v1.9.9
