### ISSUE TITLE
New lines in class description

### ISSUE THREAD

**Issue by RichDijk** [lambdamusic/Ontospy#98]
I have added multiple annotation values to bestDesiption including new line  chars.
In the template I have added a filter |linebreaks to the description section.

This does not have the expected result. Do I need to do more?

Regards, Richard

**Comment by lambdamusic** [comment]
Can you provide a reproducible example? 

NOTE `bestDescription` is simply a utility method for getting the first ('best') available description string for an RDF entity. E.g. `RDFS.comment` or `DCTERMS.description`.

**Comment by lambdamusic** [comment]
PS newlines are now rendered in HTML docs - see https://github.com/lambdamusic/Ontospy/releases/tag/v1.9.9
